{{- define "banking-library-chart.externalsecrets" -}}
kind: ExternalSecret
metadata:
  name: {{ include "banking-library-chart.appname" . }}-common-new-relic
spec:
  backendType: secretsManager
  region: us-east-1
  data:
    - name: licenseKey
      property: licenseKey
      {{- if (eq .Values.releaseStage "staging") }}
      key: staging-cyb-common-new-relic
      {{- else if (eq .Values.releaseStage "production") }}
      key: production-cyb-common-new-relic
  {{- end }}
  {{- end -}}