{{- define "banking-library-chart.hpa" -}}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "banking-library-chart.fqappname" . }}
  labels:
    app.kubernetes.io/name: {{ include "banking-library-chart.appname" . }}
spec:
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: {{ include "banking-library-chart.fqappname" . }}
{{- with .Values.autoscale }}
  minReplicas: {{ .minReplicas }}
  maxReplicas: {{ .maxReplicas }}
  metrics:
{{- end}}
{{- with .Values.autoscale.targetPercentage }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ .memory }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .cpu }}
{{- end }}
{{- end }}