{{- define "banking-library-chart.ingress" -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "banking-library-chart.fqappname" . }}
  labels:
    app.kubernetes.io/name: {{ include "banking-library-chart.appname" . }}
  annotations:
    kubernetes.io/ingress.class: nginx-internal
    nginx.ingress.kubernetes.io/rewrite-target: /
    certmanager.k8s.io/cluster-issuer: letsencrypt-production
    certmanager.k8s.io/acme-challenge-type: dns01
{{- if (eq .Values.releaseStage "production") }}
    certmanager.k8s.io/acme-dns01-provider: cloudflare
spec:
  tls:
    - secretName: moneylion-tls-production
      hosts:
        - "*.moneylion.com"
  rules:
    - host: "{{ include "banking-library-chart.fqappname" . }}.moneylion.com"
{{- else }}
    certmanager.k8s.io/acme-dns01-provider: route53-dev
spec:
  tls:
    - secretName: moneylion-tls-development
      hosts:
        - "*.moneylion.io"
  rules:
    - host: "{{ include "banking-library-chart.fqappname" . }}.moneylion.io"
{{- end }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ include "banking-library-chart.fqappname" . }}-stable
              servicePort: {{ .Values.service.port }}
{{- end -}}
{{/*  TODO: merge the hosts section by using variables in values files */}}