{{ define "banking-library-chart.service" }}
{{ if eq .Values.isCanary true }}
{{$stableArgs := dict "ServiceSuffix" "-stable" }}
{{ include "banking-library-chart.generate-service" (merge (dict "Args" $stableArgs) . ) }}
---
{{$canaryArgs := dict "ServiceSuffix" "-canary" }}
{{ include "banking-library-chart.generate-service" (merge (dict "Args" $canaryArgs) . ) }}
{{ else }}
{{$args := dict "ServiceSuffix" "" }}
{{ include "banking-library-chart.generate-service" (merge (dict "Args" $args) . ) }}
{{ end }}
{{ end }}