{{/*
Create a frieldly app name.
We truncate at 63 chars because some Kubernetes name fields are limited to this (by the DNS naming spec).
*/}}
{{- define "banking-library-chart.appname" -}}
{{- if .Values.appName }}
{{- .Values.appName | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- required "value for .Values.appName is not set" "" }}
{{- end }}
{{- end }}

{{/*
Create a fully qualified app name of form <environment>-<application name>.
We truncate at 63 chars because some Kubernetes name fields are limited to this (by the DNS naming spec).
*/}}
{{- define "banking-library-chart.fqappname" -}}
{{- if eq .Values.releaseStage "production" }}
{{- .Values.appName | trunc 63 | trimSuffix "-" }}
{{- else }}
{{-  printf "%s-%s" .Values.releaseStage .Values.appName | trunc 63 | trimSuffix "-" }}
{{- end }}
{{- end }}

{{- define "banking-library-chart.generate-service" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "banking-library-chart.fqappname" . }}{{.Args.ServiceSuffix}}
  labels:
    app.kubernetes.io/name: {{ include "banking-library-chart.appname" . }}
    helm.sh/chart: {{ include "banking-library-chart.appname" . }}-0.0.1
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    register-with-spring-boot-admin: "true"
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
{{- if eq .Values.isCanary true }}
    app: {{ include "banking-library-chart.appname" . }}
{{- else }}
    app.kubernetes.io/name: {{ include "banking-library-chart.appname" . }}
    app.kubernetes.io/instance: {{ include "banking-library-chart.fqappname" . }}
{{- end }}
{{- end }}